name: geomet
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.6.0
  - asttokens=3.0.0
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.3
  - bokeh=3.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - branca=0.6.0
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - cartopy=0.22.0
  - certifi=2025.7.14
  - cffi=1.17.1
  - cfitsio=3.470
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.1
  - configparser=5.0.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.10.6
  - geotiff=1.7.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - hdf4=4.2.13
  - hdf5=1.14.5
  - holoviews=1.21.0
  - hvplot=0.11.3
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kealib=1.5.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libboost=1.82.0
  - libcurl=8.14.1
  - libdeflate=1.22
  - libffi=3.4.4
  - libgdal=3.6.2
  - libglib=2.84.2
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzip=1.8.0
  - linkify-it-py=2.0.0
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - minizip=4.0.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - owslib=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - panel=1.7.0
  - param=2.2.1
  - parso=0.8.4
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.7
  - poppler=24.09.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyviz_comms=3.0.2
  - pywin32=308
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - requests=2.32.4
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=78.1.1
  - shapely=2.0.6
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - uc-micro-py=1.0.1
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xarray=2025.4.0
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
